obj-$(CONFIG_FT8716_ROSY)	+= focaltech_core.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_ex_fun.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_ex_mode.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_flash.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_gesture.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_i2c.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_sensor.o
obj-$(CONFIG_FT8716_ROSY)	+= focaltech_flash/
